import { TwoFactorAuthenticationSetupResult } from 'app/core/models/account/security/two-factor-authentication-setup-result.model';

/**
 * Two factor authentication state model for the store.
 */
export interface TwoFactorAuthenticationStateModel {
	/**
	 * Shared key generated by the server.
	 */
	sharedKey: string;
	/**
	 * Uri generated by the server used to display QR bar code
	 */
	authenticatorUri: string;
	/**
	 * Result of two factor authenticator setup.
	 */
	authenticatorResult: TwoFactorAuthenticationSetupResult;
}
